# Change what you need to.
skullprotect:
# Unowned settings
# Only change the head name in brand new servers.
# check out MHF heads!
  unowned:
    name: Wilderness
    head: MHF_Cake
  groups:
    head: MHF_Villager
#  
# Which blocks can still be interacted with on foreign ground? 
  interaction:
    blocks: ''
# Donkeys/mules are HORSE too
    entities: 'HORSE'
#  
# Landmark settings
  landmark:
    radius: 10
#  
# Economy settings (Economy requires Vault!)
  economy:
    useeconomy: true
    newdaymessage: 'A new day! Yay!'
# 
#   you can use: 
#     number of [plots], player [money]
#     [+],[-],[*],[/],[^],[(],[)]
#     spaces will be ignored during calculation
    tax: '5 * plots'
    landmarkprice: 'plots + money / 10'
    claimprice: 'plots / 10'
    maxclaim: 'money / 10'
#  
#  if players can't pay tax, apply effect? (duration in ticks)
#  in a group all members are affected.
    punishment:
        use: true
        effect: CONFUSION
        amplifier: 1
        duration: 200
#
  compatibility:       
#  /sp all/get will drop skull on ground instead of giving directly if set to true
    dropall: false
