name: skullprotect
main: de.bruuff.skullprotect.skullprotect
version: 0.4
author: bruuff
commands:
  sp:
    usage: /sp
    description: Basic command
  sp all:
    usage: /sp all
    description: Gives you all markers you can use
  sp clear:
    usage: /sp clear
    description: Removes all markers in your inventory
  sp get:
    usage: /sp get [player/group]
    description: Gets a marker for a specific player     
  group <group>:
    usage: /group <group>
    description: show group info
    aliases: [g]
  group <group> deposit:
    usage: /group <group> deposit  <amount>
    description: Deposit to your groups.
  group <group> withdraw:
    usage: /group <group> withdraw <amount>
    description: Withdraw from your groups (op).    
  group <group> rename <newname>:
    usage: /group rename <group> <newname>
    description: Renames group.
  group <group> add <player>:
    usage: /group add <group> <player>
    description: Adds players to your Group
  group <group> rank <player> <rank>:
    usage: /group rank <group> <player> <rank>
    description: Promotes players in your Group
  group <group> leave:
    usage: /group leave <group>
    description: Leaves the group
  group <group> remove <player>:
    usage: /group remove <group> <player>
    description: Removes players from your Group   
  group <group> toggle <permission>:
    usage: /group <group> toggle <permission>
    description: Toggle group permissions
  group new <group>:
    usage: /group new <groupname>
    description: Creates a new group 
  group list:
    usage: /group list
    description: Lists Groups    
  private:
    usage: /private
    description: Shows info about private property
    aliases: [p]
  private prices:
    usage: /private prices
    description: Lists prices for everything.
  private prices:
    usage: /private toggle
    description: Toggle private plot permissions  

    
permissions:
  skullprotect.*:
    description: Admin override.
    children:
      skullprotect.place: true
      skullprotect.break: true
      skullprotect.interact: true
      skullprotect.group: true
      skullprotect.get: true
  skullprotect.place.*:
    description: Build everywhere.
    default: op
    children:
      skullprotect.place.skull: true
      skullprotect.place.block: true
  skullprotect.place.skull.*:
    description: place every skull everywhere.
    default: op
    children:
      skullprotect.place.skull.own: true
      skullprotect.place.skull.foreign: true
  skullprotect.place.skull.own:
    description: place own skulls everywhere.
    default: true
  skullprotect.place.skull.foreign:
    description: place foreign skulls everywhere.
    default: op
  skullprotect.place.blocks:
    description: place blocks (no skulls) everywhere.
    default: op
  skullprotect.break.*:
    description: Break everywhere.
    default: op
    children:
      skullprotect.break.skull: true
      skullprotect.break.block: true
  skullprotect.break.skull.*:
    description: break every skull everywhere.
    default: op
    children:
      skullprotect.place.break.own: true
      skullprotect.place.break.foreign: true
  skullprotect.break.skull.own:
    description: break own skulls everywhere.
    default: true
  skullprotect.break.skull.foreign:
    description: break foreign skulls everywhere.
    default: op
  skullprotect.break.blocks:
    description: break blocks (no skulls) everywhere.
    default: op
  skullprotect.interact.*:
    description: Interact everywhere.
    default: op
    children:
      skullprotect.interact.own: true
      skullprotect.interact.foreign: true  
  skullprotect.interact.own:
    description: Interact where you have access.
    default: true
  skullprotect.interact.foreign:
    description: Interact everywhere.
    default: op     
  skullprotect.group.*:
    description: Edit every group.
    default: op
    children:
      skullprotect.group.new: true
      skullprotect.group.info: true    
      skullprotect.group.own: true
      skullprotect.group.foreign: true
  skullprotect.group.new:
    description: Can create a new group.
    default: true
  skullprotect.group.info:
    description: Can create a new group.
    default: true
  skullprotect.group.own.*:
    description: Operator access in own group
    default: op
    children:
      skullprotect.group.own.operator: true
      skullprotect.group.own.assistant: true
      skullprotect.group.own.member: true
  skullprotect.group.own.operator:
    description: Operator access in own group
    default: op
  skullprotect.group.own.assistant:
    description: Assistant access in own groups
    default: op
  skullprotect.group.own.member:
    description: Member access in own groups
    default: true
  skullprotect.group.foreign.*:
    description: Operator access in any group
    default: op
    children:
      skullprotect.group.foreign.operator: true
      skullprotect.group.foreign.assistant: true
      skullprotect.group.foreign.member: true
  skullprotect.group.foreign.operator:
    description: Operator access in any group
    default: op
  skullprotect.group.foreign.assistant:
    description: Assistant access in any group
    default: op
  skullprotect.group.foreign.member:
    description: Member access in any group
    default: op
  skullprotect.get.*:
    description: Get all skull that you request.
    default: op
    children:
      skullprotect.get.marker: true
      skullprotect.get.starter: true
  skullprotect.get.marker.*:
    description: Get all skull that you request.
    default: op
    children:
      skullprotect.get.marker.own: true
      skullprotect.get.marker.group: true
      skullprotect.get.marker.unowned: true
      skullprotect.get.marker.foreign: true
  skullprotect.get.marker.own:
    description: Can get your own skull.
    default: true
  skullprotect.get.marker.group:
    description: Can get your own groups skull.
    default: true
  skullprotect.get.marker.unowned:
    description: Can get unowned/wilderness skull.
    default: true
  skullprotect.get.marker.foreign:
    description: Get all skull that you request.
    default: op
  skullprotect.get.starter.*:
    description: Get all skull that you request.
    default: op
    children:
      skullprotect.get.starter.own: true
      skullprotect.get.starter.group: true
      skullprotect.get.starter.unowned: true
      skullprotect.get.starter.foreign: true
  skullprotect.get.starter.own:
    description: Can get your own skull.
    default: true
  skullprotect.get.starter.group:
    description: Can get your own groups skull.
    default: true
  skullprotect.get.starter.unowned:
    description: Can get unowned/wilderness skull.
    default: true
  skullprotect.get.starter.foreign:
    description: Get all skull that you request.
    default: op